baseURL = 'https://thanhdk.net'
languageCode = 'en-us'
title = "Thanh Dinh"
theme = "hugo-coder"
#theme = "hugo-bearblog"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "blog/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"

[markup.highlight]
style = "github-dark"

[params]
  author = "Thanh Dinh"
  info = "Chief Engineer at Holistics"
  description = "Thanh Dinh's personal website"
  keywords = "blog,developer,personal"
  #avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2017

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false
  dateFormat = "January 2, 2006"

[[module.mounts]]
source = 'images'
target = 'static/images'
